### ISSUE TITLE
Use BenchmarkDotNet

### ISSUE THREAD

**Issue by davidfowl** [danielpalme/IocPerformance#98] opened 2018-04-21 20:44 UTC
Love this benchmark!

Change the custom benchmarking infrastructure to use BDN, it's the de-factor benchmarking tech for .NET projects now and it'll likely produce more accurate results and more detailed measurements (like allocations etc).

/cc @adamsitnik @AndreyAkinshin @mattwarren

**Comment by dadhi** [comment] 2018-04-21 23:35
Here is decent inheritor BM using the BDN:
https://ipjohnson.github.io/DotNet.DependencyInjectionBenchmarks/

/cc @ipjohnson

**Comment by davidfowl** [comment] 2018-04-22 01:31
Wow that’s pretty awesome. Also some of these containers are near native speed (same as without a container), I need to see what they do under the covers.

**Comment by danielpalme** [comment] 2018-04-22 07:45
Duplicate of #77

**Closed by danielpalme** 2018-04-22 07:45 UTC
